apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-prediction
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: market-prediction
  template:
    metadata:
      labels:
        app: market-prediction
    spec:
      containers:
      - name: market-prediction
        image: your-registry.azurecr.io/market-prediction-service:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: FLASK_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
