apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-prediction
  namespace: fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-prediction
  template:
    metadata:
      labels:
        app: market-prediction
    spec:
      containers:
        - name: market-prediction
          image: public.ecr.aws/z1z0w2y6/market-prediction:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: FLASK_ENV
              value: "production"
            - name: PYTHONUNBUFFERED
              value: "1"
          livenessProbe:
            httpGet:
              path: /data
              port: 5000
            initialDelaySeconds: 60  # Increased delay
            periodSeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /data
              port: 5000
            initialDelaySeconds: 30  # Increased delay
            periodSeconds: 10